### ISSUE TITLE
Motion Commander Tutorial Discrepancy

### ISSUE THREAD

**Issue by Itai51** [bitcraze/discussions#1421]
### Discussed in https://github.com/orgs/bitcraze/discussions/1417

<div type='discussions-op-text'>

<sup>Originally posted by **Itai51** June 20, 2024</sup>
Hello Crazyflie community,

I am following the motion commander example from [this link](https://www.bitcraze.io/documentation/repository/crazyflie-lib-python/master/user-guides/sbs_motion_commander/). In the first section, "Step 1: Security before flying", I successfully run the code and get the following output:
`1
Deck is attached!`

However, when I try to run the example from the second section, "Step 2: Take off function", I get the following output (after the function times out):
`No flow deck detected!`

I've checked the wiring and tried reading through the code. I even tried deleting this condition, only for an erratic flight to take place.

What are possible reasons for the disparity?

Thank you! </div>

**Comment by knmcguire** [comment]
I'll close this since we will discuss this in discussions
