### ISSUE TITLE
How to log files on SDCard Deck?

### ISSUE THREAD

**Issue by Rwik2000** [bitcraze/discussions#497]
I tried the following link from the documentation:
https://www.bitcraze.io/products/micro-sd-card-deck/

I am unable to toggle `usd.logging` variable between 1/0. How do we change the variable's value while the crazyflie is on? 

Here is my config.txt file:

~~~
25 # buffer size in bytes
log_ # file name
1 # enable on startup (0/1)
on:fixedFrequency
250 # frequency
1 # mode (0: disabled, 1: synchronous stabilizer, 2: asynchronous)

acc.x
acc.y
acc.z
gyro.x
gyro.y
gyro.z
baro.asl
baro.temp
baro.pressure 
~~~

Even though, I enable the startup variable, but it seems it is not able to log.

**Comment by knmcguire** [comment]
The config.txt parser is very simple so there might be something in there it can not handle.

Have you tried to remove the extra enter between #mode and the first variable

**Comment by Rwik2000** [comment]
I will try to remove the white space.
How do I toggle the usd.logging variable? Do I need to turn it to 0, in order to save the log files? If so, how do I do that?
