### ISSUE TITLE
Error Could not save cache , no writable directory

### ISSUE THREAD

**Issue by mvtkurd** [bitcraze/discussions#67]
Hi @krichardsson 
I'm trying to flash ai deck esp but I got this error : Error Could not save cache , no writable directory
I'm using VM and docker and also I attached this image to make it more clear .

![Screenshot 2022-05-07 201806](https://user-images.githubusercontent.com/32674939/167266856-772fa13a-8432-4ac0-8c4e-777cecd34587.jpg)

**Comment by mvtkurd** [comment]
Hi @knmcguire 

I've followed the tutorial and this is the output of cfclient console:
As you see, there's no `ESP32: I (910) SYS: Initialized` in console but the LED1 blink with frequency 2Hz.
And AIDECK-ROUTER : Not setting up WIFI !


![second](https://user-images.githubusercontent.com/32674939/171211825-a0626571-0b8d-49f8-9577-6a537b124cd0.jpg)

**Comment by evoggy** [comment]
I think that maybe the VM is causing issues for this. Could you please try to update the STM32 firmware of the crazyflie using the cfloader to see if this works?

**Comment by mvtkurd** [comment]
Hi @evoggy ,

I cloned the latest release of firmware (2022.05) and the firmware has been built and flashed correctly by radio dongle but now how can I check the wifi has been set up ?

![4](https://user-images.githubusercontent.com/32674939/171378585-9a4f499e-a64c-4301-a61f-f82ab094ff0a.jpg)

**Comment by knmcguire** [comment]
I'm converting this to discussions as this is not yet a bug report yet, so you can find it here: discussions.bitcraze.io
